services:
  web: 
    build:
      context: app
      target: dev-envs
    stop_signal: SIGINT
    ports: 
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - redis
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: matchmaking
  redis:
    image: "redis"
    ports:
      - "6379:6379"  