version: '3'

services:
  web:
    build: ./docker
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: matchmaking
  redis:
    image: "redis"
    ports:
      - "6379:6379"